services:
  api:
    build:
      target: dev
    develop:
      watch:
        - action: sync
          path: ./app/src
          target: /app/src
        - action: rebuild
          path: ./app/package.json

  db:
    ports:
      - "${DB_PORT_HOST}:5432"