services:
  api:
    build:
      target: dev
    ports:
      - "${API_PORT}:3000"
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    develop:
      watch:
        - action: sync
          path: ./app/src
          target: /app/src
        - action: rebuild
          path: ./app/package.json

  db:
    ports:
      - "${DB_PORT_HOST}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}